import { Inter } from 'next/font/google';
import { Metadata } from 'next/head';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <head>
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        />
        <meta
          name="description"
          content={metadata.description}
        />
        <title>{metadata.title}</title>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </>
  );
}
